/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import abstractSyntaxTree.Program;
import finalCodePackage.FinalCodeGenerator;
import intermediateCode.Cuadruplo;
import intermediateCode.IntermediateCodeGenerator;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.Scanner;
import visitor.*;

/**
 *
 * @author Albertyson
 */
public class formPrincipal extends javax.swing.JFrame {
    SemanticTable tablaSimbolos = new SemanticTable();
    /**
     * Creates new form fomrPrincipal
     */
    public formPrincipal() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgTabla = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtSimbolos = new javax.swing.JTable();
        txtFileName = new javax.swing.JTextField();
        btnParse = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFile = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taIntermedio = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taFinal = new javax.swing.JTextArea();
        btnTablaSimbolo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuReadFile = new javax.swing.JMenuItem();
        mnuLexer = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();

        jtSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ámbito", "Tipo", "Dirección", "Es función", "Tipo Retorno", "Parámetros", "my scope"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtSimbolos);
        if (jtSimbolos.getColumnModel().getColumnCount() > 0) {
            jtSimbolos.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtSimbolos.getColumnModel().getColumn(1).setPreferredWidth(50);
            jtSimbolos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtSimbolos.getColumnModel().getColumn(3).setPreferredWidth(80);
            jtSimbolos.getColumnModel().getColumn(4).setPreferredWidth(80);
            jtSimbolos.getColumnModel().getColumn(5).setPreferredWidth(100);
            jtSimbolos.getColumnModel().getColumn(6).setPreferredWidth(400);
        }

        javax.swing.GroupLayout dlgTablaLayout = new javax.swing.GroupLayout(dlgTabla.getContentPane());
        dlgTabla.getContentPane().setLayout(dlgTablaLayout);
        dlgTablaLayout.setHorizontalGroup(
            dlgTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgTablaLayout.setVerticalGroup(
            dlgTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFileName.setEnabled(false);

        btnParse.setText("Parsear");
        btnParse.setEnabled(false);
        btnParse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParseMouseClicked(evt);
            }
        });
        btnParse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParseActionPerformed(evt);
            }
        });

        btnClean.setText("Limpiar");
        btnClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCleanMouseClicked(evt);
            }
        });

        txtFile.setColumns(20);
        txtFile.setRows(5);
        txtFile.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFile.setEnabled(false);
        jScrollPane1.setViewportView(txtFile);

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane2.setViewportView(txtOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Fuente y errores", jPanel1);

        taIntermedio.setColumns(20);
        taIntermedio.setRows(5);
        jScrollPane3.setViewportView(taIntermedio);

        taFinal.setColumns(20);
        taFinal.setRows(5);
        jScrollPane4.setViewportView(taFinal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Intermedio y Final", jPanel2);

        btnTablaSimbolo.setText("Ver tabla de símbolos");
        btnTablaSimbolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTablaSimboloMouseClicked(evt);
            }
        });

        jMenu2.setText("Opciones");

        mnuReadFile.setText("Leer Archivo .adb");
        mnuReadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReadFileActionPerformed(evt);
            }
        });
        jMenu2.add(mnuReadFile);

        mnuLexer.setText("Generar lexer");
        mnuLexer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLexerActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLexer);

        mnuExit.setText("Salir");
        jMenu2.add(mnuExit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFileName)
                        .addGap(18, 18, 18)
                        .addComponent(btnParse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClean)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTablaSimbolo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean)
                    .addComponent(btnTablaSimbolo)
                    .addComponent(btnParse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuReadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReadFileActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new File("./src/mainPackage/"));
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                currentFile = fc.getSelectedFile();
                txtFileName.setText(currentFile.getPath());
                btnParse.setEnabled(true);
                FileReader fr = new FileReader(currentFile);
                BufferedReader br = new BufferedReader(fr);
                txtFile.setText("");
                String linea= "";
                int lineNumber = 1;
                txtFile.setTabSize(4);
                while ((linea = br.readLine())!=null) {
                    txtFile.append(lineNumber + "\t");
                    txtFile.append(linea);
                    txtFile.append("\n");
                    lineNumber++;
                }
            } else {
                txtFileName.setText("");
                btnParse.setEnabled(true);
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_mnuReadFileActionPerformed

    private void mnuLexerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLexerActionPerformed
        // TODO add your handling code here:
        try {
            //pasa la salida estándar al textarea
            PrintStream printStream = new PrintStream(new CustomOutputStream(txtOutput));
            System.setOut(printStream);
            System.setErr(printStream);
            
            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new File("./"));
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File lexerFile = fc.getSelectedFile();
                generarLexer(lexerFile.getPath());
                JOptionPane.showMessageDialog(null, "Se ha generado el lexer", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            txtOutput.setText(e.getMessage());
        }

    }//GEN-LAST:event_mnuLexerActionPerformed

    private void btnParseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParseMouseClicked
        // TODO add your handling code here:
        try {
            PrintStream printStream = new PrintStream(new CustomOutputStream(txtOutput));
            System.setOut(printStream);
            System.setErr(printStream);
            parser p = new parser(new Lexer2(new FileReader(currentFile.getPath())));
            Object result = p.parse().value;
            if(result instanceof Program){
                Program programa = (Program)result;
                tablaSimbolos = new SemanticTable();
                SemanticAnalysis analysis =new SemanticAnalysis(tablaSimbolos);
                programa.accept(analysis);
                if(analysis.hasErrors()){
                    System.out.println("Errores Semanticos, se descontrola: aiuda");
                }else{
                    System.out.println("Listo para generar codigo intermedio");
                    ArrayList<Cuadruplo> cuadruplos = new ArrayList();
                    IntermediateCodeGenerator icg = new IntermediateCodeGenerator(programa,cuadruplos,taIntermedio,tablaSimbolos);
                    programa.generate(icg);
                    //CÓDIGO FINAL
                    FinalCodeGenerator fcg = new FinalCodeGenerator(icg.cuadruplos,tablaSimbolos,taFinal);
                    fcg.inicio();
                    fcg.cuerpo();
                    fcg.print();
                }                
            }
//            btnShowTree.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnParseMouseClicked

    private void btnCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanMouseClicked
        // TODO add your handling code here:
        txtOutput.setText("");
        taIntermedio.setText("");
        taFinal.setText("");
    }//GEN-LAST:event_btnCleanMouseClicked

    private void btnParseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParseActionPerformed

    private void btnTablaSimboloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTablaSimboloMouseClicked
        // TODO add your handling code here:
        actualizarTabla();
        dlgTabla.setModal(true);
        dlgTabla.pack();
        dlgTabla.setVisible(true);
    }//GEN-LAST:event_btnTablaSimboloMouseClicked

    private void actualizarTabla(){
//        DefaultTableModel tModel = new DefaultTableModel();
        DefaultTableModel tModel = (DefaultTableModel) jtSimbolos.getModel();
        
        while(tModel.getRowCount()>0){
            tModel.removeRow(tModel.getRowCount()-1);
        }
        for (int i = 0; i < tablaSimbolos.getSymbols().size(); i++) {
            SemanticTableNode nodoActual = tablaSimbolos.getSymbols().get(i);
            if(nodoActual instanceof SemanticVariableTableNode){
                SemanticVariableTableNode var = (SemanticVariableTableNode) nodoActual;
                String tipo = var.getType().getClass().getSimpleName();
                tModel.addRow(new Object[]{var.getName(),var.getScope(),var.getType().getClass().getName().replace("abstractSyntaxTree.",""),var.getDirection()+"","No","",""});
            }
            if(nodoActual instanceof SemanticFunctionTableNode){
                SemanticFunctionTableNode fun = (SemanticFunctionTableNode) nodoActual;
                String tipoRetorno = fun.getReturnType().getClass().getSimpleName();
                String parametrosBuffer = "";
                for(int j=0; j< fun.getParams().size(); j++){
                    SemanticVariableTableNode param = fun.getParams().get(j);
                    parametrosBuffer += param.getName() + ":" + param.getType().getClass().getSimpleName() + (j==fun.getParams().size()-1?"":", ");
                }
                tModel.addRow(new Object[]{fun.getName(),fun.getScope(),"","","Si",tipoRetorno,parametrosBuffer,fun.myScope});
            }
        }
        jtSimbolos.setModel(tModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    public void generarLexer(String path) {
        File f = new File(path);
        jflex.Main.generate(f);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnParse;
    private javax.swing.JButton btnTablaSimbolo;
    private javax.swing.JDialog dlgTabla;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtSimbolos;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLexer;
    private javax.swing.JMenuItem mnuReadFile;
    private javax.swing.JTextArea taFinal;
    private javax.swing.JTextArea taIntermedio;
    private javax.swing.JTextArea txtFile;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
    File currentFile;
}
