/* The following code was generated by JFlex 1.6.1 */

package mainPackage;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./src/mainPackage/lexer.flex</tt>
 */
class Lexer2 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\5\1\3\1\2\1\11\1\12\1\1\16\5\4\0\1\36\1\0"+
    "\1\55\1\0\1\4\3\0\1\50\1\51\1\47\1\46\1\54\1\14"+
    "\1\53\1\45\1\6\11\7\1\41\1\52\1\43\1\42\1\44\2\0"+
    "\1\21\1\40\1\17\1\15\1\16\1\25\1\37\1\35\1\24\2\4"+
    "\1\20\1\4\1\26\1\31\1\34\1\4\1\22\1\23\1\30\1\32"+
    "\1\4\1\33\1\27\2\4\1\0\1\56\2\0\1\10\1\0\1\21"+
    "\1\40\1\17\1\15\1\16\1\25\1\37\1\35\1\24\2\4\1\20"+
    "\1\4\1\26\1\31\1\34\1\4\1\22\1\23\1\30\1\32\1\4"+
    "\1\33\1\27\2\4\4\0\6\5\1\13\32\5\2\0\4\4\4\0"+
    "\1\4\2\0\1\5\7\0\1\4\4\0\1\4\5\0\27\4\1\0"+
    "\37\4\1\0\70\4\2\24\115\4\1\23\u0142\4\4\0\14\4\16\0"+
    "\5\4\7\0\1\4\1\0\1\4\21\0\160\5\5\4\1\0\2\4"+
    "\2\0\4\4\10\0\1\4\1\0\3\4\1\0\1\4\1\0\24\4"+
    "\1\0\123\4\1\0\213\4\1\0\5\5\2\0\236\4\11\0\46\4"+
    "\2\0\1\4\7\0\47\4\7\0\1\4\1\0\55\5\1\0\1\5"+
    "\1\0\2\5\1\0\2\5\1\0\1\5\10\0\33\4\5\0\3\4"+
    "\15\0\5\5\6\0\1\4\4\0\13\5\5\0\53\4\37\5\4\0"+
    "\2\4\1\5\143\4\1\0\1\4\10\5\1\0\6\5\2\4\2\5"+
    "\1\0\4\5\2\4\12\5\3\4\2\0\1\4\17\0\1\5\1\4"+
    "\1\5\36\4\33\5\2\0\131\4\13\5\1\4\16\0\12\5\41\4"+
    "\11\5\2\4\4\0\1\4\5\0\26\4\4\5\1\4\11\5\1\4"+
    "\3\5\1\4\5\5\22\0\31\4\3\5\104\0\1\4\1\0\13\4"+
    "\67\0\33\5\1\0\4\5\66\4\3\5\1\4\22\5\1\4\7\5"+
    "\12\4\2\5\2\0\12\5\1\0\7\4\1\0\7\4\1\0\3\5"+
    "\1\0\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0\1\4"+
    "\3\0\4\4\2\0\1\5\1\4\7\5\2\0\2\5\2\0\3\5"+
    "\1\4\10\0\1\5\4\0\2\4\1\0\3\4\2\5\2\0\12\5"+
    "\4\4\7\0\1\4\5\0\3\5\1\0\6\4\4\0\2\4\2\0"+
    "\26\4\1\0\7\4\1\0\2\4\1\0\2\4\1\0\2\4\2\0"+
    "\1\5\1\0\5\5\4\0\2\5\2\0\3\5\3\0\1\5\7\0"+
    "\4\4\1\0\1\4\7\0\14\5\3\4\1\5\13\0\3\5\1\0"+
    "\11\4\1\0\3\4\1\0\26\4\1\0\7\4\1\0\2\4\1\0"+
    "\5\4\2\0\1\5\1\4\10\5\1\0\3\5\1\0\3\5\2\0"+
    "\1\4\17\0\2\4\2\5\2\0\12\5\1\0\1\4\17\0\3\5"+
    "\1\0\10\4\2\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4"+
    "\1\0\5\4\2\0\1\5\1\4\7\5\2\0\2\5\2\0\3\5"+
    "\10\0\2\5\4\0\2\4\1\0\3\4\2\5\2\0\12\5\1\0"+
    "\1\4\20\0\1\5\1\4\1\0\6\4\3\0\3\4\1\0\4\4"+
    "\3\0\2\4\1\0\1\4\1\0\2\4\3\0\2\4\3\0\3\4"+
    "\3\0\14\4\4\0\5\5\3\0\3\5\1\0\4\5\2\0\1\4"+
    "\6\0\1\5\16\0\12\5\11\0\1\4\7\0\3\5\1\0\10\4"+
    "\1\0\3\4\1\0\27\4\1\0\12\4\1\0\5\4\3\0\1\4"+
    "\7\5\1\0\3\5\1\0\4\5\7\0\2\5\1\0\2\4\6\0"+
    "\2\4\2\5\2\0\12\5\22\0\2\5\1\0\10\4\1\0\3\4"+
    "\1\0\27\4\1\0\12\4\1\0\5\4\2\0\1\5\1\4\7\5"+
    "\1\0\3\5\1\0\4\5\7\0\2\5\7\0\1\4\1\0\2\4"+
    "\2\5\2\0\12\5\1\0\2\4\17\0\2\5\1\0\10\4\1\0"+
    "\3\4\1\0\51\4\2\0\1\4\7\5\1\0\3\5\1\0\4\5"+
    "\1\4\10\0\1\5\10\0\2\4\2\5\2\0\12\5\12\0\6\4"+
    "\2\0\2\5\1\0\22\4\3\0\30\4\1\0\11\4\1\0\1\4"+
    "\2\0\7\4\3\0\1\5\4\0\6\5\1\0\1\5\1\0\10\5"+
    "\22\0\2\5\15\0\60\4\1\5\2\4\7\5\4\0\10\4\10\5"+
    "\1\0\12\5\47\0\2\4\1\0\1\4\2\0\2\4\1\0\1\4"+
    "\2\0\1\4\6\0\4\4\1\0\7\4\1\0\3\4\1\0\1\4"+
    "\1\0\1\4\2\0\2\4\1\0\4\4\1\5\2\4\6\5\1\0"+
    "\2\5\1\4\2\0\5\4\1\0\1\4\1\0\6\5\2\0\12\5"+
    "\2\0\4\4\40\0\1\4\27\0\2\5\6\0\12\5\13\0\1\5"+
    "\1\0\1\5\1\0\1\5\4\0\2\5\10\4\1\0\44\4\4\0"+
    "\24\5\1\0\2\5\5\4\13\5\1\0\44\5\11\0\1\5\71\0"+
    "\53\4\24\5\1\4\12\5\6\0\6\4\4\5\4\4\3\5\1\4"+
    "\3\5\2\4\7\5\3\4\4\5\15\4\14\5\1\4\17\5\2\0"+
    "\46\4\1\0\1\4\5\0\1\4\2\0\53\4\1\0\u014d\4\1\0"+
    "\4\4\2\0\7\4\1\0\1\4\1\0\4\4\2\0\51\4\1\0"+
    "\4\4\2\0\41\4\1\0\4\4\2\0\7\4\1\0\1\4\1\0"+
    "\4\4\2\0\17\4\1\0\71\4\1\0\4\4\2\0\103\4\2\0"+
    "\3\5\40\0\20\4\20\0\125\4\14\0\u026c\4\2\0\21\4\1\0"+
    "\32\4\5\0\113\4\3\0\3\4\17\0\15\4\1\0\4\4\3\5"+
    "\13\0\22\4\3\5\13\0\22\4\2\5\14\0\15\4\1\0\3\4"+
    "\1\0\2\5\14\0\64\4\40\5\3\0\1\4\3\0\2\4\1\5"+
    "\2\0\12\5\41\0\3\5\2\0\12\5\6\0\130\4\10\0\51\4"+
    "\1\5\1\4\5\0\106\4\12\0\35\4\3\0\14\5\4\0\14\5"+
    "\12\0\12\5\36\4\2\0\5\4\13\0\54\4\4\0\21\5\7\4"+
    "\2\5\6\0\12\5\46\0\27\4\5\5\4\0\65\4\12\5\1\0"+
    "\35\5\2\0\13\5\6\0\12\5\15\0\1\4\130\0\5\5\57\4"+
    "\21\5\7\4\4\0\12\5\21\0\11\5\14\0\3\5\36\4\15\5"+
    "\2\4\12\5\54\4\16\5\14\0\44\4\24\5\10\0\12\5\3\0"+
    "\3\4\12\5\44\4\122\0\3\5\1\0\25\5\4\4\1\5\4\4"+
    "\3\5\2\4\11\0\300\4\47\5\25\0\4\5\u0116\4\2\0\6\4"+
    "\2\0\46\4\2\0\6\4\2\0\10\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\37\4\2\0\65\4\1\0\7\4\1\0\1\4"+
    "\3\0\3\4\1\0\7\4\3\0\4\4\2\0\6\4\4\0\15\4"+
    "\5\0\3\4\1\0\7\4\16\0\5\5\30\0\1\11\1\11\5\5"+
    "\20\0\2\4\23\0\1\4\13\0\5\5\5\0\6\5\1\0\1\4"+
    "\15\0\1\4\20\0\15\4\3\0\33\4\25\0\15\5\4\0\1\5"+
    "\3\0\14\5\21\0\1\4\4\0\1\4\2\0\12\4\1\0\1\4"+
    "\3\0\5\4\6\0\1\4\1\0\1\4\1\0\1\4\1\0\4\4"+
    "\1\0\13\4\2\0\4\4\5\0\5\4\4\0\1\4\21\0\51\4"+
    "\u0a77\0\57\4\1\0\57\4\1\0\205\4\6\0\4\4\3\5\2\4"+
    "\14\0\46\4\1\0\1\4\5\0\1\4\2\0\70\4\7\0\1\4"+
    "\17\0\1\5\27\4\11\0\7\4\1\0\7\4\1\0\7\4\1\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0"+
    "\40\5\57\0\1\4\u01d5\0\3\4\31\0\11\4\6\5\1\0\5\4"+
    "\2\0\5\4\4\0\126\4\2\0\2\5\2\0\3\4\1\0\132\4"+
    "\1\0\4\4\5\0\51\4\3\0\136\4\21\0\33\4\65\0\20\4"+
    "\u0200\0\u19b6\4\112\0\u51cd\4\63\0\u048d\4\103\0\56\4\2\0\u010d\4"+
    "\3\0\20\4\12\5\2\4\24\0\57\4\1\5\4\0\12\5\1\0"+
    "\31\4\7\0\1\5\120\4\2\5\45\0\11\4\2\0\147\4\2\0"+
    "\4\4\1\0\4\4\14\0\13\4\115\0\12\4\1\5\3\4\1\5"+
    "\4\4\1\5\27\4\5\5\20\0\1\4\7\0\64\4\14\0\2\5"+
    "\62\4\21\5\13\0\12\5\6\0\22\5\6\4\3\0\1\4\4\0"+
    "\12\5\34\4\10\5\2\0\27\4\15\5\14\0\35\4\3\0\4\5"+
    "\57\4\16\5\16\0\1\4\12\5\46\0\51\4\16\5\11\0\3\4"+
    "\1\5\10\4\2\5\2\0\12\5\6\0\27\4\3\0\1\4\1\5"+
    "\4\0\60\4\1\5\1\4\3\5\2\4\2\5\5\4\2\5\1\4"+
    "\1\5\1\4\30\0\3\4\2\0\13\4\5\5\2\0\3\4\2\5"+
    "\12\0\6\4\2\0\6\4\2\0\6\4\11\0\7\4\1\0\7\4"+
    "\221\0\43\4\10\5\1\0\2\5\2\0\12\5\6\0\u2ba4\4\14\0"+
    "\27\4\4\0\61\4\u2104\0\u016e\4\2\0\152\4\46\0\7\4\14\0"+
    "\5\4\5\0\1\4\1\5\12\4\1\0\15\4\1\0\5\4\1\0"+
    "\1\4\1\0\2\4\1\0\2\4\1\0\154\4\41\0\u016b\4\22\0"+
    "\100\4\2\0\66\4\50\0\15\4\3\0\20\5\20\0\7\5\14\0"+
    "\2\4\30\0\3\4\31\0\1\4\6\0\5\4\1\0\207\4\2\0"+
    "\1\5\4\0\1\4\13\0\12\5\7\0\32\4\4\0\1\4\1\0"+
    "\32\4\13\0\131\4\3\0\6\4\2\0\6\4\2\0\6\4\2\0"+
    "\3\4\3\0\2\4\3\0\2\4\22\0\3\5\4\0\14\4\1\0"+
    "\32\4\1\0\23\4\1\0\2\4\1\0\17\4\2\0\16\4\42\0"+
    "\173\4\105\0\65\4\210\0\1\5\202\0\35\4\3\0\61\4\57\0"+
    "\37\4\21\0\33\4\65\0\36\4\2\0\44\4\4\0\10\4\1\0"+
    "\5\4\52\0\236\4\2\0\12\5\u0356\0\6\4\2\0\1\4\1\0"+
    "\54\4\1\0\2\4\3\0\1\4\2\0\27\4\252\0\26\4\12\0"+
    "\32\4\106\0\70\4\6\0\2\4\100\0\1\4\3\5\1\0\2\5"+
    "\5\0\4\5\4\4\1\0\3\4\1\0\33\4\4\0\3\5\4\0"+
    "\1\5\40\0\35\4\203\0\66\4\12\0\26\4\12\0\23\4\215\0"+
    "\111\4\u03b7\0\3\5\65\4\17\5\37\0\12\5\20\0\3\5\55\4"+
    "\13\5\2\0\1\5\22\0\31\4\7\0\12\5\6\0\3\5\44\4"+
    "\16\5\1\0\12\5\100\0\3\5\60\4\16\5\4\4\13\0\12\5"+
    "\u04a6\0\53\4\15\5\10\0\12\5\u0936\0\u036f\4\221\0\143\4\u0b9d\0"+
    "\u042f\4\u33d1\0\u0239\4\u04c7\0\105\4\13\0\1\4\56\5\20\0\4\5"+
    "\15\4\u4060\0\2\4\u2163\0\5\5\3\0\26\5\2\0\7\5\36\0"+
    "\4\5\224\0\3\5\u01bb\0\125\4\1\0\107\4\1\0\2\4\2\0"+
    "\1\4\2\0\2\4\2\0\4\4\1\0\14\4\1\0\1\4\1\0"+
    "\7\4\1\0\101\4\1\0\4\4\2\0\10\4\1\0\7\4\1\0"+
    "\34\4\1\0\4\4\1\0\5\4\1\0\1\4\3\0\7\4\1\0"+
    "\u0154\4\2\0\31\4\1\0\31\4\1\0\37\4\1\0\31\4\1\0"+
    "\37\4\1\0\31\4\1\0\37\4\1\0\31\4\1\0\37\4\1\0"+
    "\31\4\1\0\10\4\2\0\62\5\u1600\0\4\4\1\0\33\4\1\0"+
    "\2\4\1\0\1\4\2\0\1\4\1\0\12\4\1\0\4\4\1\0"+
    "\1\4\1\0\1\4\6\0\1\4\4\0\1\4\1\0\1\4\1\0"+
    "\1\4\1\0\3\4\1\0\2\4\1\0\1\4\2\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\0\1\4\1\0\2\4\1\0"+
    "\1\4\2\0\4\4\1\0\7\4\1\0\4\4\1\0\4\4\1\0"+
    "\1\4\1\0\12\4\1\0\21\4\5\0\3\4\1\0\5\4\1\0"+
    "\21\4\u1144\0\ua6d7\4\51\0\u1035\4\13\0\336\4\u3fe2\0\u021e\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\5\36\0\140\5\200\0\360\5\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\2\4\1\5\16\3\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\1\1\20\1\21\1\22\1\23\1\24\3\0"+
    "\1\2\7\3\1\25\1\26\1\27\11\3\1\30\7\3"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\2\43\1\4\2\3\1\44\2\3\1\45"+
    "\2\3\1\0\2\3\1\46\1\3\1\47\1\50\3\3"+
    "\1\51\3\3\1\52\1\53\3\3\1\54\1\3\1\55"+
    "\1\56\2\3\1\0\3\3\1\57\1\60\1\61\1\62"+
    "\5\3\1\63\2\3\1\0\1\64\1\65\1\3\1\66"+
    "\1\3\1\67\2\3\1\70\1\3\1\71\3\3\1\72"+
    "\1\73\2\3\1\74\1\75\1\3\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\136\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a"+
    "\0\136\0\u0439\0\u0468\0\u0497\0\136\0\u04c6\0\136\0\136"+
    "\0\136\0\u04f5\0\136\0\136\0\u0524\0\136\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\274\0\274\0\u0787\0\u07b6\0\u07e5\0\u0814"+
    "\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\274\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\136\0\136"+
    "\0\136\0\136\0\136\0\136\0\136\0\136\0\136\0\136"+
    "\0\u0aa6\0\u05b1\0\u0ad5\0\u0b04\0\u0b33\0\274\0\u0b62\0\u0b91"+
    "\0\274\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\274\0\u0cab"+
    "\0\274\0\274\0\u0cda\0\u0d09\0\u0d38\0\274\0\u0d67\0\u0d96"+
    "\0\u0dc5\0\274\0\274\0\u0df4\0\u0e23\0\u0e52\0\274\0\u0e81"+
    "\0\274\0\274\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b"+
    "\0\274\0\274\0\274\0\274\0\u0fca\0\u0ff9\0\u1028\0\u1057"+
    "\0\u1086\0\274\0\u10b5\0\u10e4\0\u1113\0\274\0\274\0\u1142"+
    "\0\274\0\u1171\0\274\0\u11a0\0\u11cf\0\274\0\u11fe\0\136"+
    "\0\u122d\0\u125c\0\u128b\0\274\0\274\0\u12ba\0\u12e9\0\274"+
    "\0\274\0\u1318\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\6"+
    "\1\3\1\5\1\3\1\11\1\12\1\13\1\6\1\14"+
    "\1\15\1\16\1\6\1\17\1\20\1\21\1\6\1\22"+
    "\1\23\1\6\1\24\1\25\1\6\1\5\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\3\1\45\2\3"+
    "\52\45\1\46\1\47\61\0\1\5\60\0\5\6\2\0"+
    "\1\6\1\0\21\6\1\0\2\6\16\0\1\50\2\0"+
    "\3\50\2\51\1\50\3\0\44\50\2\0\3\50\2\10"+
    "\1\52\3\0\43\50\14\0\1\53\46\0\5\6\2\0"+
    "\1\6\1\0\1\6\1\54\17\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\3\6\1\55\5\6\1\56"+
    "\1\57\6\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\14\6\1\60\4\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\11\6\1\61\7\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\1\6\1\62\17\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\6\6"+
    "\1\63\1\6\1\64\1\65\7\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\3\6\1\66\1\67\7\6"+
    "\1\70\1\71\3\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\1\6\1\72\12\6\1\73\1\74\3\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\5\6"+
    "\1\75\12\6\1\76\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\5\6\1\77\7\6\1\100\3\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\20\6\1\101"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\5\6"+
    "\1\102\7\6\1\103\3\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\1\6\1\104\17\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\1\6\1\105\12\6"+
    "\1\106\4\6\1\0\2\6\60\0\1\107\56\0\1\110"+
    "\56\0\1\111\56\0\1\112\63\0\1\113\62\0\1\114"+
    "\3\0\1\45\2\0\52\45\24\0\1\115\3\0\1\116"+
    "\1\0\1\117\24\0\1\120\7\0\2\121\47\0\1\50"+
    "\2\0\3\50\2\122\1\50\3\0\43\50\6\0\2\123"+
    "\47\0\1\53\1\4\1\5\54\53\4\0\5\6\2\0"+
    "\1\6\1\0\2\6\1\124\16\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\6\6\1\125\12\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\1\126\20\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\7\6"+
    "\1\127\11\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\14\6\1\130\4\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\1\131\20\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\13\6\1\132\5\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\13\6\1\133"+
    "\5\6\1\134\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\14\6\1\135\4\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\3\6\1\136\15\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\5\6\1\137\13\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\11\6\1\140"+
    "\7\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\16\6\1\141\2\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\13\6\1\142\5\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\3\6\1\143\15\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\15\6\1\144"+
    "\3\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\1\6\1\145\17\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\13\6\1\146\5\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\1\6\1\147\5\6\1\150"+
    "\11\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\14\6\1\151\4\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\13\6\1\152\5\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\13\6\1\153\5\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\21\6\1\0"+
    "\1\154\1\6\22\0\5\6\2\0\1\6\1\0\14\6"+
    "\1\155\4\6\1\0\2\6\24\0\2\121\1\50\54\0"+
    "\2\123\1\52\52\0\5\6\2\0\1\6\1\0\3\6"+
    "\1\156\15\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\1\6\1\157\5\6\1\160\11\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\13\6\1\161\5\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\17\6"+
    "\1\162\1\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\15\6\1\163\3\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\1\6\1\164\17\6\1\0\2\6"+
    "\47\0\1\165\31\0\5\6\2\0\1\6\1\0\4\6"+
    "\1\166\14\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\6\6\1\167\12\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\2\6\1\170\16\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\3\6\1\171\15\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\1\6"+
    "\1\172\17\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\11\6\1\173\7\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\11\6\1\174\7\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\3\6\1\175\15\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\2\6"+
    "\1\176\16\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\7\6\1\177\11\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\3\6\1\200\15\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\4\6\1\201\14\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\10\6"+
    "\1\202\10\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\5\6\1\203\13\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\21\6\1\0\1\204\1\6\50\0"+
    "\1\205\30\0\5\6\2\0\1\6\1\0\13\6\1\206"+
    "\5\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\1\6\1\207\17\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\13\6\1\210\5\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\1\6\1\211\17\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\1\6\1\212"+
    "\17\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\11\6\1\213\7\6\1\0\2\6\22\0\5\6\2\0"+
    "\1\6\1\0\1\6\1\214\17\6\1\0\2\6\22\0"+
    "\5\6\2\0\1\6\1\0\5\6\1\215\13\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\11\6\1\216"+
    "\7\6\1\0\2\6\22\0\5\6\2\0\1\6\1\0"+
    "\1\6\1\217\17\6\1\0\2\6\46\0\1\220\32\0"+
    "\5\6\2\0\1\6\1\0\7\6\1\221\11\6\1\0"+
    "\2\6\22\0\5\6\2\0\1\6\1\0\1\222\20\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\4\6"+
    "\1\223\14\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\1\6\1\224\17\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\5\6\1\225\13\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\14\6\1\226\4\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\15\6"+
    "\1\227\3\6\1\0\2\6\22\0\5\6\2\0\1\6"+
    "\1\0\11\6\1\230\7\6\1\0\2\6\22\0\5\6"+
    "\2\0\1\6\1\0\11\6\1\231\7\6\1\0\2\6"+
    "\22\0\5\6\2\0\1\6\1\0\5\6\1\232\13\6"+
    "\1\0\2\6\22\0\5\6\2\0\1\6\1\0\1\6"+
    "\1\233\17\6\1\0\2\6\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4935];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\23\1\1\11\3\1\1\11"+
    "\1\1\3\11\1\1\2\11\1\1\1\11\1\1\3\0"+
    "\34\1\12\11\13\1\1\0\30\1\1\0\17\1\1\0"+
    "\12\1\1\11\13\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer2(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2898) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext() + ">");
            }
          case 63: break;
          case 2: 
            { /* ignore */
            }
          case 64: break;
          case 3: 
            { System.out.println("<ID, \"" + yytext() + "\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.ID, yytext());
            }
          case 65: break;
          case 4: 
            { System.out.println("<INT, \"" + yytext() + "\" " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.NUMEROENTERO, new Integer(Integer.parseInt(yytext())));
            }
          case 66: break;
          case 5: 
            { System.out.println("<OPRESTA, \"-\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERRESTA);
            }
          case 67: break;
          case 6: 
            { System.out.println("<DOS PUNTOS "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.DOSPUNTOS);
            }
          case 68: break;
          case 7: 
            { System.out.println("<OPREL, \"=\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERIGUAL);
            }
          case 69: break;
          case 8: 
            { System.out.println("<OPREL, \"<\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERMENOR);
            }
          case 70: break;
          case 9: 
            { System.out.println("<OPREL, \">\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERMAYOR);
            }
          case 71: break;
          case 10: 
            { System.out.println("<OPDIV, \"/\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERDIVISION);
            }
          case 72: break;
          case 11: 
            { System.out.println("<OPSUMA, \"+\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERSUMA);
            }
          case 73: break;
          case 12: 
            { System.out.println("<OPMULT, \"*\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERMULTIPLICACION);
            }
          case 74: break;
          case 13: 
            { System.out.println("<ABRIRPARENTESIS "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.PARIZQ);
            }
          case 75: break;
          case 14: 
            { System.out.println("<CERRARPARENTESIS "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.PARDER);
            }
          case 76: break;
          case 15: 
            { System.out.println("<PUNTOCOMA "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.PUNTOCOMA);
            }
          case 77: break;
          case 16: 
            { System.out.println("<COMA "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.COMA);
            }
          case 78: break;
          case 17: 
            { string.setLength(0); yybegin(STRING);
            }
          case 79: break;
          case 18: 
            { string.append( yytext() );
            }
          case 80: break;
          case 19: 
            { yybegin(YYINITIAL); System.out.println("<STRING, \"" + string.toString() + "\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.CADENA, string.toString());
            }
          case 81: break;
          case 20: 
            { string.append('\\');
            }
          case 82: break;
          case 21: 
            { System.out.println("<IS "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.IS);
            }
          case 83: break;
          case 22: 
            { System.out.println("<IF "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.IF);
            }
          case 84: break;
          case 23: 
            { System.out.println("<IN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.IN);
            }
          case 85: break;
          case 24: 
            { System.out.println("<OPBOOL, \"or\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.NOT);
            }
          case 86: break;
          case 25: 
            { System.out.println("<ASIG, \":=\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERASIG);
            }
          case 87: break;
          case 26: 
            { System.out.println("<OPREL, \"<=\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERMENORIGUAL);
            }
          case 88: break;
          case 27: 
            { System.out.println("<OPREL, \">=\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERMAYORIGUAL);
            }
          case 89: break;
          case 28: 
            { System.out.println("<OPREL, \"/=\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERDISTINTO);
            }
          case 90: break;
          case 29: 
            { System.out.println("<OPEXP, \"**\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OPERPOTENCIA);
            }
          case 91: break;
          case 30: 
            { System.out.println("<RANGO "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.DOBLEPUNTO);
            }
          case 92: break;
          case 31: 
            { string.append('\r');
            }
          case 93: break;
          case 32: 
            { string.append('\n');
            }
          case 94: break;
          case 33: 
            { string.append('\t');
            }
          case 95: break;
          case 34: 
            { string.append('\"');
            }
          case 96: break;
          case 35: 
            { System.out.println("<FLOAT, \"" + yytext() + "\" " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.NUMEROFLOAT, new Double(Double.parseDouble(yytext())));
            }
          case 97: break;
          case 36: 
            { System.out.println("<END " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.END);
            }
          case 98: break;
          case 37: 
            { System.out.println("<OPBOOL, \"and\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.AND);
            }
          case 99: break;
          case 38: 
            { System.out.println("<FOR " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.FOR);
            }
          case 100: break;
          case 39: 
            { System.out.println("<NEW "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.NEW);
            }
          case 101: break;
          case 40: 
            { System.out.println("<OPBOOL, \"not\" "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OR);
            }
          case 102: break;
          case 41: 
            { System.out.println("<OUT "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.OUT);
            }
          case 103: break;
          case 42: 
            { System.out.println("<PUT "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.PUT);
            }
          case 104: break;
          case 43: 
            { System.out.println("<GET "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.GET);
            }
          case 105: break;
          case 44: 
            { System.out.println("<ELSE " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.ELSE);
            }
          case 106: break;
          case 45: 
            { System.out.println("<EXIT " + (yyline+1)+":"+yycolumn+">"); return symbol(sym.EXIT);
            }
          case 107: break;
          case 46: 
            { System.out.println("<LOOP "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.LOOP);
            }
          case 108: break;
          case 47: 
            { System.out.println("<NULL "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.NULL);
            }
          case 109: break;
          case 48: 
            { System.out.println("<TRUE "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.TRUE);
            }
          case 110: break;
          case 49: 
            { System.out.println("<THEN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.THEN);
            }
          case 111: break;
          case 50: 
            { System.out.println("<WHEN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.WHEN);
            }
          case 112: break;
          case 51: 
            { System.out.println("<ELSE " + (yyline + 1) + ":" + yycolumn + ">"); return symbol(sym.ELSIF);
            }
          case 113: break;
          case 52: 
            { System.out.println("<FLOAT "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.FLOAT);
            }
          case 114: break;
          case 53: 
            { System.out.println("<FALSE "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.FALSE);
            }
          case 115: break;
          case 54: 
            { System.out.println("<WHILE "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.WHILE);
            }
          case 116: break;
          case 55: 
            { System.out.println("<BEGIN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.BEGIN);
            }
          case 117: break;
          case 56: 
            { System.out.println("<RETURN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.RETURN);
            }
          case 118: break;
          case 57: 
            { System.out.println("<IN_OUT "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.INOUT);
            }
          case 119: break;
          case 58: 
            { System.out.println("<DECLARE " + (yyline+1) + ":" + yycolumn + ">"); return symbol(sym.DECLARE);
            }
          case 120: break;
          case 59: 
            { System.out.println("<INTEGER "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.INTEGER);
            }
          case 121: break;
          case 60: 
            { System.out.println("<BOOLEAN "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.BOOLEAN);
            }
          case 122: break;
          case 61: 
            { System.out.println("<FUNCTION "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.FUNCTION);
            }
          case 123: break;
          case 62: 
            { System.out.println("<PROCEDURE "+(yyline+1)+":"+yycolumn+">"); return symbol(sym.PROCEDURE);
            }
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
