package mainPackage;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 28 19:10:44 CST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 59;
  public static final int DOSPUNTOS = 53;
  public static final int WHEN = 17;
  public static final int FUNCTION = 8;
  public static final int OPERASIG = 32;
  public static final int OPERMAYOR = 35;
  public static final int WITH = 27;
  public static final int OPERMULTIPLICACION = 42;
  public static final int PUT = 25;
  public static final int OPERMAYORIGUAL = 38;
  public static final int INTEGER = 22;
  public static final int PUNTOCOMA = 50;
  public static final int OUT = 13;
  public static final int FOR = 7;
  public static final int INOUT = 21;
  public static final int NOT = 46;
  public static final int AND = 45;
  public static final int IS = 29;
  public static final int USE = 28;
  public static final int OR = 47;
  public static final int IN = 18;
  public static final int GET = 26;
  public static final int BEGIN = 30;
  public static final int LOOP = 20;
  public static final int EXIT = 6;
  public static final int IF = 10;
  public static final int AMPERSAND = 55;
  public static final int OPERPOTENCIA = 44;
  public static final int ID = 60;
  public static final int DOBLEPUNTO = 57;
  public static final int PARIZQ = 48;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int RETURN = 15;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int COMA = 52;
  public static final int CADENA = 58;
  public static final int OPERPUNTERO = 33;
  public static final int NULL = 12;
  public static final int MOD = 31;
  public static final int OPERRESTA = 41;
  public static final int DECLARE = 2;
  public static final int OPERDIVISION = 43;
  public static final int ELSE = 4;
  public static final int PUNTO = 51;
  public static final int OPERIGUAL = 36;
  public static final int GOTO = 9;
  public static final int WHILE = 19;
  public static final int OPERDISTINTO = 37;
  public static final int FLOAT = 24;
  public static final int NUMERAL = 54;
  public static final int THEN = 16;
  public static final int END = 5;
  public static final int PARDER = 49;
  public static final int APOSTROFE = 56;
  public static final int PROCEDURE = 14;
  public static final int OPERSUMA = 40;
  public static final int DO = 3;
  public static final int OPERMENORIGUAL = 39;
  public static final int OPERMENOR = 34;
}

