
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 18 23:01:25 CST 2016
//----------------------------------------------------

package mainPackage;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 51;
  public static final int WHEN = 22;
  public static final int FUNCTION = 16;
  public static final int OPERASIG = 31;
  public static final int OPERMAYOR = 33;
  public static final int OPERMULTIPLICACION = 40;
  public static final int PUT = 27;
  public static final int ELSIF = 11;
  public static final int CASE = 62;
  public static final int OPERMAYORIGUAL = 36;
  public static final int INTEGER = 2;
  public static final int PUNTOCOMA = 48;
  public static final int OUT = 18;
  public static final int NEGATIVO = 52;
  public static final int FOR = 12;
  public static final int INOUT = 26;
  public static final int CHARACTER = 5;
  public static final int NUMEROENTERO = 66;
  public static final int NOT = 45;
  public static final int AND = 43;
  public static final int IS = 29;
  public static final int CARACTER = 65;
  public static final int OR = 44;
  public static final int IN = 23;
  public static final int GET = 28;
  public static final int BEGIN = 30;
  public static final int LOOP = 25;
  public static final int EXIT = 15;
  public static final int IF = 9;
  public static final int AMPERSAND = 56;
  public static final int OPERPOTENCIA = 42;
  public static final int ID = 63;
  public static final int DOBLEPUNTO = 49;
  public static final int PARIZQ = 46;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 20;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int CADENA = 64;
  public static final int OPERPUNTERO = 58;
  public static final int PIPE = 53;
  public static final int NULL = 17;
  public static final int MOD = 59;
  public static final int OPERRESTA = 39;
  public static final int DECLARE = 13;
  public static final int NUMEROFLOAT = 67;
  public static final int OPERDIVISION = 41;
  public static final int ELSE = 10;
  public static final int OTHERS = 61;
  public static final int PUNTO = 54;
  public static final int OPERIGUAL = 34;
  public static final int GOTO = 60;
  public static final int WHILE = 24;
  public static final int OPERDISTINTO = 35;
  public static final int FLOAT = 4;
  public static final int NUMERAL = 55;
  public static final int THEN = 21;
  public static final int END = 14;
  public static final int STRING = 6;
  public static final int PARDER = 47;
  public static final int FALSE = 8;
  public static final int PROCEDURE = 19;
  public static final int DO = 57;
  public static final int OPERSUMA = 38;
  public static final int OPERMENORIGUAL = 37;
  public static final int OPERMENOR = 32;
}

