
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package mainPackage;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 46;
  public static final int WHEN = 17;
  public static final int FUNCTION = 12;
  public static final int OPERASIG = 26;
  public static final int OPERMAYOR = 28;
  public static final int OPERMULTIPLICACION = 35;
  public static final int PUT = 22;
  public static final int ELSIF = 8;
  public static final int CASE = 52;
  public static final int OPERMAYORIGUAL = 31;
  public static final int INTEGER = 2;
  public static final int PUNTOCOMA = 43;
  public static final int OUT = 13;
  public static final int NEGATIVO = 47;
  public static final int FOR = 9;
  public static final int INOUT = 21;
  public static final int NUMEROENTERO = 55;
  public static final int NOT = 40;
  public static final int AND = 38;
  public static final int IS = 24;
  public static final int OR = 39;
  public static final int IN = 18;
  public static final int GET = 23;
  public static final int BEGIN = 25;
  public static final int LOOP = 20;
  public static final int EXIT = 11;
  public static final int IF = 6;
  public static final int OPERPOTENCIA = 37;
  public static final int ID = 53;
  public static final int DOBLEPUNTO = 44;
  public static final int PARIZQ = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 15;
  public static final int TRUE = 57;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int CADENA = 54;
  public static final int OPERPUNTERO = 49;
  public static final int PIPE = 48;
  public static final int MOD = 50;
  public static final int OPERRESTA = 34;
  public static final int NUMEROFLOAT = 56;
  public static final int OPERDIVISION = 36;
  public static final int ELSE = 7;
  public static final int OTHERS = 51;
  public static final int OPERIGUAL = 29;
  public static final int WHILE = 19;
  public static final int OPERDISTINTO = 30;
  public static final int FLOAT = 4;
  public static final int THEN = 16;
  public static final int END = 10;
  public static final int STRING = 5;
  public static final int FALSE = 58;
  public static final int PARDER = 42;
  public static final int PROCEDURE = 14;
  public static final int OPERSUMA = 33;
  public static final int OPERMENORIGUAL = 32;
  public static final int OPERMENOR = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "BOOLEAN",
  "FLOAT",
  "STRING",
  "IF",
  "ELSE",
  "ELSIF",
  "FOR",
  "END",
  "EXIT",
  "FUNCTION",
  "OUT",
  "PROCEDURE",
  "RETURN",
  "THEN",
  "WHEN",
  "IN",
  "WHILE",
  "LOOP",
  "INOUT",
  "PUT",
  "GET",
  "IS",
  "BEGIN",
  "OPERASIG",
  "OPERMENOR",
  "OPERMAYOR",
  "OPERIGUAL",
  "OPERDISTINTO",
  "OPERMAYORIGUAL",
  "OPERMENORIGUAL",
  "OPERSUMA",
  "OPERRESTA",
  "OPERMULTIPLICACION",
  "OPERDIVISION",
  "OPERPOTENCIA",
  "AND",
  "OR",
  "NOT",
  "PARIZQ",
  "PARDER",
  "PUNTOCOMA",
  "DOBLEPUNTO",
  "COMA",
  "DOSPUNTOS",
  "NEGATIVO",
  "PIPE",
  "OPERPUNTERO",
  "MOD",
  "OTHERS",
  "CASE",
  "ID",
  "CADENA",
  "NUMEROENTERO",
  "NUMEROFLOAT",
  "TRUE",
  "FALSE"
  };
}

